version: "3.8"
services:
  redis:
    image: "redis:alpine"
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - $PWD/redis-data:/var/lib/redis
  server:
    image: lemonface0309/productify-backend:latest
    build: ./
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
      - /app/node_modules
    links:
      - redis
    environment:
      - NODE_ENV=development
      - PORT=8080
      - REDIS_PORT="6379"
      - REDIS_URL=redis
    depends_on:
      - redis
